# Generated by Django 4.0.4 on 2022-05-13 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portfolio_main.maintechnology', verbose_name='Project main technology'),
        ),
    ]
